project_id = "ecodis-app"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]

[db]
port = 54322
major_version = 17

[auth]
enabled = true
site_url = "https://ecodis-app-six.vercel.app"
additional_redirect_urls = [
  "https://ecodis-app-six.vercel.app/reset-password",
  "https://ecodis-app-gaius-team.vercel.app/reset-password",
  "http://localhost:5173/reset-password",
  "http://127.0.0.1:4173/reset-password",
]

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
max_frequency = "1m0s"
otp_length = 8
otp_expiry = 3600
