export const seedMessages = [
  { type: "audio", title: "La puissance de la priere dans la vie du disciple", author: "Pasteur Jean", category: "Predications", duration: "45:30", description: "Un enseignement profond sur l'importance de la priere quotidienne.", thumbnail: "", mediaPath: "", createdAt: "2026-02-27T10:00:00Z" },
  { type: "audio", title: "Comment etudier la Bible efficacement", author: "Pasteur Marie", category: "Enseignements", duration: "32:15", description: "Des methodes pratiques pour approfondir votre comprehension des Ecritures.", thumbnail: "", mediaPath: "", createdAt: "2026-02-25T10:00:00Z" },
  { type: "audio", title: "Louange et adoration : une arme spirituelle", author: "Frere David", category: "Louanges", duration: "28:45", description: "Decouvrez comment la louange et l'adoration sont des armes puissantes.", thumbnail: "", mediaPath: "", createdAt: "2026-02-23T10:00:00Z" },
  { type: "audio", title: "Mon temoignage de conversion", author: "Soeur Ruth", category: "Temoignages", duration: "18:20", description: "Un temoignage inspirant de transformation.", thumbnail: "", mediaPath: "", createdAt: "2026-02-20T10:00:00Z" },
  { type: "audio", title: "La foi qui deplace les montagnes", author: "Pasteur Jean", category: "Predications", duration: "52:10", description: "Apprenons a exercer notre foi avec puissance.", thumbnail: "", mediaPath: "", createdAt: "2026-02-18T10:00:00Z" },
  { type: "audio", title: "Les dons du Saint-Esprit", author: "Pasteur Esther", category: "Enseignements", duration: "40:05", description: "Un tour d'horizon complet des dons spirituels.", thumbnail: "", mediaPath: "", createdAt: "2026-02-15T10:00:00Z" },
  { type: "video", title: "Culte dominical - Marcher dans la foi", author: "Pasteur Jean", category: "Cultes", duration: "1:25:30", description: "Culte complet avec louange et predication.", thumbnail: "https://images.unsplash.com/photo-1624499843552-7347d9f6d285?w=600", mediaPath: "", createdAt: "2026-02-27T08:00:00Z" },
  { type: "video", title: "Seminaire sur le discipulat - Session 1", author: "Pasteur Marie", category: "Seminaires", duration: "58:15", description: "Premiere session du seminaire sur les fondements du discipulat.", thumbnail: "https://images.unsplash.com/photo-1760367120345-2b96c53de838?w=600", mediaPath: "", createdAt: "2026-02-24T08:00:00Z" },
  { type: "video", title: "Formation des leaders - Module 3", author: "Frere Paul", category: "Formations", duration: "1:10:45", description: "Module 3 de la formation des leaders.", thumbnail: "https://images.unsplash.com/photo-1660176982561-0d9e8705877d?w=600", mediaPath: "", createdAt: "2026-02-20T08:00:00Z" },
  { type: "video", title: "Conference annuelle - L'appel de Dieu", author: "Evangeliste Samuel", category: "Conferences", duration: "2:05:00", description: "Conference annuelle sur le theme de l'appel de Dieu.", thumbnail: "https://images.unsplash.com/photo-1624499843552-7347d9f6d285?w=600", mediaPath: "", createdAt: "2026-02-15T08:00:00Z" },
  { type: "text", title: "Les beatitudes : un chemin de bonheur", author: "Pasteur Jean", category: "Etudes bibliques", duration: "", description: "Jesus nous montre un chemin de bonheur qui passe par l'humilite.", thumbnail: "", mediaPath: "", createdAt: "2026-02-28T10:00:00Z" },
  { type: "text", title: "Meditation du matin : Psaume 23", author: "Soeur Ruth", category: "Meditations", duration: "", description: "L'Eternel est mon berger, je ne manquerai de rien.", thumbnail: "", mediaPath: "", createdAt: "2026-02-27T06:00:00Z" },
  { type: "text", title: "Comment devenir un disciple engage", author: "Pasteur Marie", category: "Articles", duration: "", description: "Le discipulat n'est pas simplement une activite, c'est un mode de vie.", thumbnail: "", mediaPath: "", createdAt: "2026-02-25T10:00:00Z" },
  { type: "text", title: "Notes : La grace suffisante de Dieu", author: "Frere Paul", category: "Notes de predication", duration: "", description: "La grace de Dieu est suffisante pour nous dans toutes nos faiblesses.", thumbnail: "", mediaPath: "", createdAt: "2026-02-23T10:00:00Z" },
  { type: "text", title: "L'importance de la communion fraternelle", author: "Pasteur Esther", category: "Articles", duration: "", description: "La vie chretienne n'est pas faite pour etre vecue seul.", thumbnail: "", mediaPath: "", createdAt: "2026-02-20T10:00:00Z" },
  { type: "text", title: "Etude : Le livre des Actes - Chapitre 2", author: "Pasteur Jean", category: "Etudes bibliques", duration: "", description: "Le jour de la Pentecote, le Saint-Esprit est descendu sur les disciples.", thumbnail: "", mediaPath: "", createdAt: "2026-02-18T10:00:00Z" },
];

export const seedSeries = [
  { title: "Formation des leaders", description: "Un programme complet de formation pour les leaders.", coverImage: "https://images.unsplash.com/photo-1629141647559-70bc6c13c7fe?w=1080", author: "Frere Paul", category: "Formation", messageIndexes: [8, 7, 9] },
  { title: "Fondements de la foi chretienne", description: "Decouvrez les bases essentielles de la foi chretienne.", coverImage: "https://images.unsplash.com/photo-1729714625765-6ad07c70038e?w=1080", author: "Pasteur Jean", category: "Enseignement", messageIndexes: [0, 4, 1, 5] },
  { title: "Etudes bibliques essentielles", description: "Plongez dans les Ecritures avec cette collection d'etudes.", coverImage: "https://images.unsplash.com/photo-1766145549011-2eccae0bf7ca?w=1080", author: "Pasteur Jean", category: "Etude biblique", messageIndexes: [10, 15, 12, 14] },
];
